# Generated by Django 4.0.5 on 2022-11-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0002_dashboard_user_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
