# Generated by Django 4.0.5 on 2022-11-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0003_dashboard_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_user',
            name='name',
        ),
    ]
