# Generated by Django 4.0.5 on 2022-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender_code', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('aboriginal_peoples', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('visible_minorities', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('person_with_disabilities', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('position_category', models.CharField(choices=[('Executive', 'Executive'), ('Senior Leader', 'Senior Leader'), ('Manager/Supervisor/Superintendent', 'Manager/Supervisor/Superintendent'), ('Foreperson', 'Foreperson'), ('Individual Contributor', 'Individual Contributor')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
