# Generated by Django 4.0.5 on 2022-11-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0009_alter_companydata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='name',
            new_name='comany_name',
        ),
    ]
