# Generated by Django 4.0.5 on 2022-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dddashboard', '0011_rename_comany_name_companydata_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard_user',
            options={'verbose_name_plural': 'Dashboard Users'},
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dddashboard.companyname'),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='user_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='aboriginal_peoples',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dddashboard.companyname'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='gender_code',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='person_with_disabilities',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='position_category',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Senior Leader', 'Senior Leader'), ('Manager/Supervisor/Superintendent', 'Manager/Supervisor/Superintendent'), ('Foreperson', 'Foreperson'), ('Individual Contributor', 'Individual Contributor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='visible_minorities',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
