# Generated by Django 4.0.5 on 2022-12-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dddashboard', '0012_alter_dashboard_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_user',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
