# Generated by Django 4.0.5 on 2022-12-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0013_alter_dashboard_user_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='company_name',
            new_name='name',
        ),
    ]
