# Generated by Django 4.0.5 on 2023-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0015_companysize_companydata_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='size',
        ),
        migrations.AddField(
            model_name='companydata',
            name='company_size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CompanySize',
        ),
    ]
